### ISSUE TITLE
seems like `Fiber::start()` does not exist anymore.

### ISSUE THREAD

**Issue by docteurklein** [amphp/green-thread#1]
I modified the code to call `Fiber::resume()` instead. Is it normal?

Also, do you know the state of fiber in php nowadays? should I invest a bit of time to maintain an impl based on ext-fiber ?

Cheers :)

**Comment by kelunik** [comment]
We won't continue using `ext-fiber` but will go with `ext-async` for Amp v3 instead.

**Comment by docteurklein** [comment]
Thanks. Replaced calls with `Concurrent\Fiber::*` equivalents and works like a charm. Closing now.
